name: Testing PullRequest Triggers
on: 
  issue_comment:
    types: created
jobs:
  # en el contexto del evento comentario no están los datos de la pull request (descripcion y ramas), tendria que obtenerlos usando la api. 
  pr_commented:
    name: PR comment
    if: ${{ github.event.issue.pull_request }} && ${{ github.base_ref }} == 'main'
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo Comment created in a pull request
          echo "${{ github.base_ref }}"
  PR_comment_context:
    name: github context
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo '$GITHUB_CONTEXT'
      - run: echo "${{ github.base_ref }}"
